//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int id { get; set; }
        public string course1 { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
