//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> nic { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> salary { get; set; }
        public string photo { get; set; }
        public string alternateText { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string personalWebsite { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
    }
}
